/** @type {import('@remix-run/dev').AppConfig} */
export default {
  ignoredRouteFiles: ["**/.*"],
  serverModuleFormat: "cjs",
  serverPlatform: "node",
  serverMinify: false,
  serverDependenciesToBundle: [
    "react-markdown",
    "lucide-react",
    "devlop",
    "hast-util-to-jsx-runtime",
    "html-url-attributes",
    "remark-parse",
    "remark-rehype",
    "unified",
    "unist-util-visit",
    "vfile",
    "mdast-util-to-hast",
    "unist-util-visit-parents",
    "vfile-message",
    "comma-separated-tokens",
    "mdast-util-from-markdown",
    "bail",
    "estree-util-is-identifier-name",
    "hast-util-whitespace",
    "property-information",
    "is-plain-obj",
    "space-separated-tokens",
    "trough",
    "unist-util-position",
    "unist-util-is",
    "unist-util-stringify-position",
    "mdast-util-to-string",
    "@ungap/structured-clone",
    "micromark",
    "micromark-util-sanitize-uri",
    "micromark-util-decode-numeric-character-reference",
    "micromark-util-decode-string",
    "micromark-util-normalize-identifier",
    "decode-named-character-reference",
    "trim-lines",
    "micromark-util-character",
    "micromark-util-encode",
    "character-entities",
    "micromark-util-combine-extensions",
    "micromark-util-subtokenize",
    "micromark-util-chunked",
    "micromark-factory-space",
    "micromark-core-commonmark",
    "micromark-util-resolve-all",
    "micromark-factory-destination",
    "micromark-factory-label",
    "micromark-util-classify-character",
    "micromark-util-html-tag-name",
    "micromark-factory-title",
    "micromark-factory-whitespace"
  ],
  future: {
    v2_errorBoundary: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
    v2_headers: true
  }
};